### ISSUE TITLE
CHR + POS for Gialluisi 

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#13]
@gaow 

```
import pandas as pd


ac1 = pd.read_table(r"C:\Users\mgrasso24\Downloads\MetaAnalysis_cc1.tbl")




def memory_usage(self, deep=False):
    result = self.map_partitions(ac1.memory_usage, deep=deep, enforce_metadata=False)
    return delayed(sum)(result.to_delayed())


column_subset = [
    "MarkerName",
    "Allele1",
    "Allele2",
    "Weight",
    "Zscore",
    "P-value",
    "Direction",
    "HetISq",
    "HetChiSq",
    "HetDf",
    "HetPVal",
]


df = pd.read_table(
    r"C:\Users\mgrasso24\Downloads\MetaAnalysis_cc1.tbl",
    usecols=column_subset,
    nrows=6917791
)
ac2 = pd.read_table(r"C:\Users\mgrasso24\Downloads\snp151.txt")


Zy = ac2
Xy = df.MarkerName
new = open("compared_data.txt", 'x')
new.write = Xy.isin(Zy)
new.close()
```

I keep.getting this error 

> 

Traceback (most recent call last):
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\main.py", line 29, in <module>
    ac2 = pd.read_table(r"C:\Users\mgrasso24\Downloads\snp151.txt")
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1289, in read_table
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    return parser.read(nrows)
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "C:\Users\mgrasso24\PycharmProjects\pythonProject2\venv\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas\_libs\parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas\_libs\parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas\_libs\parsers.pyx", line 1083, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas\_libs\parsers.pyx", line 1183, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas\_libs\parsers.pyx", line 1744, in pandas._libs.parsers._try_int64
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 256. KiB for an array with shape (32768,) and data type int64

Do you have any ideas on how to fix this?

**Comment by gaow** [comment]
@mgrasso24 I need more information about this. I"m taking the conversation on slack so we can communicate real time.
